version: "3"
services:
 
  frontend:
    image: harshitdevjs388/music_labs_frontend_v7:latest
    stdin_open: true
    ports:
      - "5173:5173"
    depends_on:
      - "api-server"
    networks:
      - music-lab
  
  api-server:
    image: harshitdevjs388/music_labs_backend_v6:latest
    ports:
      - "8000:8000"
    depends_on:
      - "redis-server"
    networks:
      - music-lab
  
  redis-server:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - music-lab

networks:
  music-lab:
    driver: bridge